/// Flutter icons RPGTRackerIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  RPGTRackerIcons
///      fonts:
///       - asset: fonts/RPGTRackerIcons.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class RPGTRackerIcons {
  RPGTRackerIcons._();

  static const _kFontFam = 'RPGTRackerIcons';
  static const String? _kFontPkg = null;

  static const IconData octopus = IconData(0xea50, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
