name: rpgtracker_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webview_flutter: ^4.2.4
  shared_preferences: ^2.2.1
  rxdart: ^0.27.7
  get_it: ^7.6.4
  jwt_decoder: ^2.0.1
  dio: ^5.3.3
  loader_overlay: ^2.3.2
  flutter_localizations:
    sdk: flutter
  i18next: ^0.7.2
  json_serializable: ^6.7.1
  flutter_tabler_icons: ^1.3.0
  json_annotation: ^4.8.1
  build_runner: ^2.4.6
  provider: ^6.0.5
  stomp_dart_client: ^1.0.0
  avatar_stack: ^1.2.0
  shimmer: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/i18n/en/
    - assets/i18n/pt-BR/
    - assets/i18n/es/

    - assets/img/

  fonts:
    - family: RPGTrackerIcons
      fonts:
        - asset: assets/icons/fonts/RPGTrackerIcons.ttf
